Bulk data release notes 40
ebi-gene-expression-group/atlas-release-notes pull request #43
Opened 2024-05-10 08:11 UTC by pmb59

2024-05-14 15:19 UTC, sfexova approved these changes

2024-05-15 10:35 UTC, ke4 requested changes
I added 2 comments. Could you please have a look at them?
Other than that it looks fine with me.
Thanks

2024-05-15 10:35 UTC, ke4 commented on release-notes/gxa/_posts/2024-05-10-40.md
We can add somewhere the added new publication, too:
[Expression Atlas update: insights from sequencing data at both bulk and single cell level](https://academic.oup.com/nar/article/52/D1/D107/7442051)

2024-05-15 10:35 UTC, ke4 commented on release-notes/gxa/_posts/2024-05-10-40.md
There were also some bugfix related some experiments's Supplementary Information tabs. I am not sure if we list here the fixed bugs.

2024-05-15 12:19 UTC, sfexova commented on release-notes/gxa/_posts/2024-05-10-40.md
Hi @ke4 - usually we wouldn't specifically mention bug fixes in the release notes, just focusing on what's new, so unless this is a bug for which we received a lot of complaints and would therefore be highly anticipated by the users I would not mention it
As for the new publication - we tweeted about the paper when it came out (which was some time ago) I think, not sure if I would mention it in the release as the paper itself is not that new if you see what I mean, we've just added it to the 'cite us' section now

2024-05-15 14:06 UTC, merged